services:
  2GIG-345-MQTT:
    build: .
    container_name: 2gig_345_mqtt
    restart: unless-stopped
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - ./config.yaml:/config.yaml:ro
